# pip install -q pyyaml h5py

import pandas as pd
import numpy as np
import re
import tensorflow as tf
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
import difflib

disease2id, model, symptom_count, extra_symptoms_to_id, symptom2id, id2disease = None, None, None, None, None,None


def clean(text):
    text = text.strip().lower()
    if len(text.split("_")) > 1:
        text = text.split("_")[1]
    if len(text.split("_")) > 0:
        text = text.split("^")[0]
    s = set(stopwords.words('english'))
    filtered_text = filter(lambda w: not w in s, text.split())
    text = " ".join(filtered_text)
    text = re.sub(r'[" "]+', "_", text)
    if len(text) > 1:
        return text


def clean_input(text):
    text = text.strip().lower()
    if len(text.split("_")) > 1:
        text = text.split("_")[1]
    if len(text.split("_")) > 0:
        text = text.split("^")[0]
    text = re.sub(r'[" "]+', " ", text)
    text = re.sub(r"[^a-z]+", " ", text)
    s = set(stopwords.words('english'))
    filtered_text = filter(lambda w: not w in s, text.split())
    text = " ".join(filtered_text)
    return text


def get_disease_id(name):
    global disease2id
    return disease2id[name]


def get_words(sentence):
    words = []
    for word in sentence.split(" "):
        words.append(word)
    for i in range(len(sentence.split(" ")) - 1):
        words.append(" ".join(sentence.split(" ")[i:i + 2]))
    for i in range(len(sentence.split(" ")) - 2):
        words.append(" ".join(sentence.split(" ")[i:i + 3]))
    # print(words)
    return words


def get_new_x(my_input):
    global disease2id, model, symptom_count, extra_symptoms_to_id, symptom2id, id2disease
    my_input = clean_input(my_input)
    new_x = [0 for i in range(symptom_count)]
    known_symptoms = 0
    for word in get_words(my_input):
        new_symptoms = difflib.get_close_matches(word, extra_symptoms_to_id.keys(), cutoff=0.8)
        if len(new_symptoms) > 0:
            print(new_symptoms)
        for new_symptom in new_symptoms:
            new_x[extra_symptoms_to_id[new_symptom]] += 1
            known_symptoms += 1
            if new_symptom in symptom2id.keys():
                new_x[extra_symptoms_to_id[new_symptom]] += 2
    return new_x


def train_model():
    global disease2id, model, symptom_count, extra_symptoms_to_id, symptom2id, id2disease
    df = pd.read_html("http://people.dbmi.columbia.edu/~friedma/Projects/DiseaseSymptomKB/index.html", skiprows=1)[0]
    df.columns = ["Disease", "Occurences", "Symptoms"]
    df.drop("Occurences", inplace=True, axis=1)
    # df.info()
    df.fillna(method='ffill', inplace=True)
    df["Disease"] = df["Disease"].astype(str)
    df["Symptoms"] = df["Symptoms"].astype(str)
    # df
    df["Disease"] = df["Disease"].map(clean)
    df["Symptoms"] = df["Symptoms"].map(clean)
    # df.isnull().values.any()
    df.dropna(inplace=True)
    df.isnull().values.any()
    # df

    disease2id = {}
    disease_count = 0
    for disease in df["Disease"]:
        if disease not in disease2id:
            disease2id[disease] = disease_count
            disease_count += 1
    # print(disease_count, disease2id)
    id2disease = {v: k for k, v in disease2id.items()}
    # print(id2disease)
    # print(disease2id.keys())
    diseases_list = list(disease2id.keys())

    symptom2id = {}
    symptom_count = 0
    for symptom in df["Symptoms"]:
        if symptom not in symptom2id:
            symptom2id[symptom] = symptom_count
            symptom_count += 1
    # print(symptom_count, symptom2id)
    id2symptom = {v: k for k, v in symptom2id.items()}
    print(id2symptom)
    symptoms_list = list(symptom2id.keys())
    # print(symptoms_list)

    grouped_df = df.groupby(by="Disease", sort=False)
    column_names = list(symptoms_list)
    column_names.extend(["Disease"])
    # print(column_names)

    new_df = pd.DataFrame(columns=column_names)
    new_df["Disease"] = diseases_list
    new_df.set_index("Disease", inplace=True)
    new_df.fillna(0, inplace=True)
    # new_df

    X = []
    for key, item in grouped_df:
        # print(key)
        for symptom in grouped_df.get_group(key)["Symptoms"]:
            new_df.loc[key, symptom] = 1
    # new_df

    new_df.index.map(get_disease_id)
    X = new_df[symptoms_list].to_numpy()
    y = new_df.index.map(get_disease_id).to_numpy()
    print(X.shape, y.shape)
    print(X[0])

    y_cat = to_categorical(y)
    y_cat.shape

    extra_symptoms_to_id = dict()

    for k, v in symptom2id.items():
        split = k.split("_")
        extra_symptoms_to_id[" ".join(split)] = v
        rev = list(split)
        rev.reverse()
        if len(split) > 1:
            extra_symptoms_to_id[" ".join(rev)] = v
            print("{} --- {}".format(k, " ".join(rev)))
            for word in split:
                print("{} --- {}".format(k, word))
                extra_symptoms_to_id[word] = v
    len(extra_symptoms_to_id)

    extra_symptoms_to_id

    my_input = "i have fever. sore throat. headache. sneeze. blackout. short of breath"
    X = np.array(X)
    y = np.array(y)
    X_tensor = tf.data.Dataset.from_tensor_slices(X)
    y_tensor = tf.data.Dataset.from_tensor_slices(y)
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(64, activation="relu"))
    model.add(tf.keras.layers.Dropout(0.7))
    model.add(tf.keras.layers.Dense(64, activation="relu"))
    model.add(tf.keras.layers.Dropout(0.7))
    model.add(tf.keras.layers.Dense(y_cat.shape[0], activation="sigmoid"))
    model.compile(loss='categorical_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    # model.fit(X, y_cat, epochs=10)
    # model.save("./estimators/model")


def predict_disease(my_input):
    global disease2id, model, symptom_count, extra_symptoms_to_id, symptom2id, id2disease
    load_variables()
    my_input = " . ".join(my_input)
    clf = tf.keras.models.load_model('./estimators/model')
    my_input = clean_input(my_input)
    new_x = get_new_x(my_input)
    known_symptoms = np.count_nonzero(new_x == 1)
    print(known_symptoms)
    return id2disease[clf.predict_classes([new_x])[0]]


def print_hello():
    print("hello")


def load_variables():
    global disease2id, model, symptom_count, extra_symptoms_to_id, symptom2id, id2disease
    symptom_count = 396
    symptom2id = {'pain_chest': 0, 'shortness_breath': 1, 'dizziness': 2, 'asthenia': 3, 'fall': 4, 'syncope': 5, 'vertigo': 6, 'sweat': 7, 'palpitation': 8, 'nausea': 9, 'angina_pectoris': 10, 'pressure_chest': 11, 'polyuria': 12, 'polydypsia': 13, 'orthopnea': 14, 'rale': 15, 'unresponsiveness': 16, 'mental_status_changes': 17, 'vomiting': 18, 'labored_breathing': 19, 'feeling_suicidal': 20, 'suicidal': 21, 'hallucinations_auditory': 22, 'feeling_hopeless': 23, 'weepiness': 24, 'sleeplessness': 25, 'motor_retardation': 26, 'irritable_mood': 27, 'blackout': 28, 'mood_depressed': 29, 'hallucinations_visual': 30, 'worry': 31, 'agitation': 32, 'tremor': 33, 'intoxication': 34, 'verbal_auditory_hallucinations': 35, 'energy_increased': 36, 'difficulty': 37, 'nightmare': 38, 'unable_concentrate': 39, 'homelessness': 40, 'hypokinesia': 41, 'dyspnea_exertion': 42, 'chest_tightness': 43, 'cough': 44, 'fever': 45, 'decreased_translucency': 46, 'productive_cough': 47, 'pleuritic_pain': 48, 'yellow_sputum': 49, 'breath_sounds_decreased': 50, 'chill': 51, 'rhonchus': 52, 'green_sputum': 53, 'non-productive_cough': 54, 'wheezing': 55, 'haemoptysis': 56, 'distress_respiratory': 57, 'tachypnea': 58, 'malaise': 59, 'night_sweat': 60, 'jugular_venous_distention': 61, 'dyspnea': 62, 'dysarthria': 63, 'speech_slurred': 64, 'facial_paresis': 65, 'hemiplegia': 66, 'seizure': 67, 'numbness': 68, 'symptom_aggravating_factors': 69, 'st_segment_elevation': 70, 'st_segment_depression': 71, 'wave_inverted': 72, 'presence_q_wave': 73, 'chest_discomfort': 74, 'bradycardia': 75, 'pain': 76, 'nonsmoker': 77, 'erythema': 78, 'hepatosplenomegaly': 79, 'pruritus': 80, 'diarrhea': 81, 'abscess_bacterial': 82, 'swelling': 83, 'apyrexial': 84, 'dysuria': 85, 'hematuria': 86, 'renal_angle_tenderness': 87, 'lethargy': 88, 'hyponatremia': 89, 'hemodynamically_stable': 90, 'difficulty_passing_urine': 91, 'consciousness_clear': 92, 'guaiac_positive': 93, 'monoclonal': 94, 'ecchymosis': 95, 'tumor_cell_invasion': 96, 'haemorrhage': 97, 'pallor': 98, 'fatigue': 99, 'heme_positive': 100, 'pain_back': 101, 'orthostasis': 102, 'arthralgia': 103, 'transaminitis': 104, 'sputum_purulent': 105, 'hypoxemia': 106, 'hypercapnia': 107, 'patient_non_compliance': 108, 'unconscious_state': 109, 'bedridden': 110, 'abdominal_tenderness': 111, 'unsteady_gait': 112, 'hyperkalemia': 113, 'urgency_micturition': 114, 'ascites': 115, 'hypotension': 116, 'enuresis': 117, 'asterixis': 118, 'muscle_twitch': 119, 'sleepy': 120, 'headache': 121, 'lightheadedness': 122, 'food_intolerance': 123, 'numbness_hand': 124, 'general_discomfort': 125, 'drowsiness': 126, 'stiffness': 127, 'prostatism': 128, 'weight_gain': 129, 'mass_body_structure': 130, 'religious_belief': 131, 'nervousness': 132, 'formication': 133, 'hot_flush': 134, 'lesion': 135, 'cushingoid_facies': 136, 'emphysematous_change': 137, 'decreased_body_weight': 138, 'hoarseness': 139, 'thicken': 140, 'spontaneous_rupture_membranes': 141, 'muscle_hypotonia': 142, 'redness': 143, 'hypesthesia': 144, 'hyperacusis': 145, 'scratch_marks': 146, 'sore_touch': 147, 'burning_sensation': 148, 'satiety_early': 149, 'throbbing_sensation_quality': 150, 'sensory_discomfort': 151, 'constipation': 152, 'pain_abdominal': 153, 'heartburn': 154, 'breech_presentation': 155, 'cyanosis': 156, 'pain_lower_limb': 157, 'cardiomegaly': 158, 'clonus': 159, 'unwell': 160, 'anorexia': 161, 'anosmia': 162, 'metastatic_lesion': 163, 'hemianopsia_homonymous': 164, 'hematocrit_decreased': 165, 'neck_stiffness': 166, 'cicatrisation': 167, 'hypometabolism': 168, 'aura': 169, 'myoclonus': 170, 'gurgle': 171, 'wheelchair_bound': 172, 'left_atrial_hypertrophy': 173, 'oliguria': 174, 'catatonia': 175, 'unhappy': 176, 'paresthesia': 177, 'gravida_0': 178, 'lung_nodule': 179, 'distended_abdomen': 180, 'ache': 181, 'macerated_skin': 182, 'heavy_feeling': 183, 'rest_pain': 184, 'sinus_rhythm': 185, 'withdraw': 186, 'behavior_hyperactive': 187, 'terrify': 188, 'photopsia': 189, 'giddy_mood': 190, 'disturbed_family': 191, 'hypersomnia': 192, 'hyperhidrosis_disorder': 193, 'mydriasis': 194, 'extrapyramidal_sign': 195, 'loose_associations': 196, 'exhaustion': 197, 'snore': 198, 'r_wave_feature': 199, 'overweight': 200, 'systolic_murmur': 201, 'asymptomatic': 202, 'splenomegaly': 203, 'bleeding_vagina': 204, 'macule': 205, 'photophobia': 206, 'painful_swallowing': 207, 'cachexia': 208, 'hypocalcemia_result': 209, 'hypothermia,_natural': 210, 'atypia': 211, 'general_unsteadiness': 212, 'throat_sore': 213, 'snuffle': 214, 'hacking_cough': 215, 'stridor': 216, 'paresis': 217, 'aphagia': 218, 'focal_seizures': 219, 'abnormal_sensation': 220, 'stupor': 221, 'fremitus': 222, "stahli's_line": 223, 'stinging_sensation': 224, 'paralyse': 225, 'hirsutism': 226, 'sniffle': 227, 'bradykinesia': 228, 'breath': 229, 'urge_incontinence': 230, 'vision_blurred': 231, 'room_spinning': 232, 'rambling_speech': 233, 'clumsiness': 234, 'decreased_stool_caliber': 235, 'hematochezia': 236, 'egophony': 237, 'neologism': 238, 'decompensation': 239, 'stool_color_yellow': 240, 'rigor_-_temperature-associated_observation': 241, 'paraparesis': 242, 'moody': 243, 'fear_falling': 244, 'spasm': 245, 'hyperventilation': 246, 'excruciating_pain': 247, 'gag': 248, 'posturing': 249, 'pulse_absent': 250, 'dysesthesia': 251, 'polymyalgia': 252, 'passed_stones': 253, 'qt_interval_prolonged': 254, 'ataxia': 255, "heberden's_node": 256, 'hepatomegaly': 257, 'sciatica': 258, 'frothy_sputum': 259, 'mass_breast': 260, 'retropulsion': 261, 'estrogen_use': 262, 'hypersomnolence': 263, 'underweight': 264, 'dullness': 265, 'red_blotches': 266, 'colic_abdominal': 267, 'hypokalemia': 268, 'hunger': 269, 'prostate_tender': 270, 'pain_foot': 271, 'urinary_hesitation': 272, 'disequilibrium': 273, 'flushing': 274, 'indifferent_mood': 275, 'urinoma': 276, 'hypoalbuminemia': 277, 'pustule': 278, 'slowing_urinary_stream': 279, 'extreme_exhaustion': 280, 'status_change': 281, 'breakthrough_pain': 282, 'pansystolic_murmur': 283, 'systolic_ejection_murmur': 284, 'stuffy_nose': 285, 'barking_cough': 286, 'rapid_shallow_breathing': 287, 'noisy_respiration': 288, 'nasal_discharge_present': 289, 'frail': 290, 'cystic_lesion': 291, 'projectile_vomiting': 292, 'heavy_legs': 293, 'titubation': 294, 'dysdiadochokinesia': 295, 'achalasia': 296, 'side_pain': 297, 'monocytosis': 298, 'posterior_rhinorrhea': 299, 'incoherent': 300, 'lameness': 301, 'clammy_skin': 302, 'mediastinal_shift': 303, 'nausea_vomiting': 304, 'awakening_early': 305, 'tenesmus': 306, 'fecaluria': 307, 'pneumatouria': 308, 'todd_paralysis': 309, 'alcoholic_withdrawal_symptoms': 310, 'myalgia': 311, 'dyspareunia': 312, 'poor_dentition': 313, 'floppy': 314, 'inappropriate_affect': 315, 'poor_feeding': 316, 'moan': 317, 'welt': 318, 'tinnitus': 319, 'hydropneumothorax': 320, 'superimposition': 321, 'feeling_strange': 322, 'uncoordination': 323, 'absences_finding': 324, 'tonic_seizures': 325, 'debilitation': 326, 'impaired_cognition': 327, 'drool': 328, 'pin-point_pupils': 329, 'tremor_resting': 330, 'groggy': 331, 'adverse_reaction': 332, 'abdominal_bloating': 333, 'fatigability': 334, 'para_2': 335, 'abortion': 336, 'intermenstrual_heavy_bleeding': 337, 'previous_pregnancies_2': 338, 'primigravida': 339, 'abnormally_hard_consistency': 340, 'proteinemia': 341, 'pain_neck': 342, 'dizzy_spells': 343, 'shooting_pain': 344, 'hyperemesis': 345, 'milky': 346, 'regurgitates_swallowing': 347, 'lip_smacking': 348, 'phonophobia': 349, 'rolling_eyes': 350, 'ambidexterity': 351, 'pulsus_paradoxus': 352, 'gravida_10': 353, 'bruit': 354, 'breath-holding_spell': 355, 'scleral_icterus': 356, 'retch': 357, 'blanch': 358, 'elation': 359, 'verbally_abusive_behavior': 360, 'transsexual': 361, 'behavior_showing_increased_motor_activity': 362, 'scar_tissue': 363, 'coordination_abnormal': 364, 'choke': 365, 'bowel_sounds_decreased': 366, 'known_drug_allergies': 367, 'low_back_pain': 368, 'charleyhorse': 369, 'sedentary': 370, 'feels_hot/feverish': 371, 'flare': 372, 'pericardial_friction_rub': 373, 'hoard': 374, 'panic': 375, 'cardiovascular_finding': 376, 'soft_tissue_swelling': 377, 'rhd_positive': 378, 'para_1': 379, 'nasal_flaring': 380, 'sneeze': 381, 'hypertonicity': 382, "murphy's_sign": 383, 'flatulence': 384, 'gasping_breath': 385, 'feces_rectum': 386, 'prodrome': 387, 'hypoproteinemia': 388, 'alcohol_binge_episode': 389, 'abdomen_acute': 390, 'air_fluid_level': 391, 'catching_breath': 392, 'large-for-dates_fetus': 393, 'immobile': 394, 'homicidal_thoughts': 395}
    disease2id = {'hypertensive_disease': 0, 'diabetes': 1, 'depression_mental': 2, 'coronary_arteriosclerosis': 3,
                  'pneumonia': 4, 'failure_heart_congestive': 5, 'accident_cerebrovascular': 6, 'asthma': 7,
                  'myocardial_infarction': 8, 'hypercholesterolemia': 9, 'infection': 10, 'infection_urinary_tract': 11,
                  'anemia': 12, 'chronic_obstructive_airway_disease': 13, 'dementia': 14, 'insufficiency_renal': 15,
                  'confusion': 16, 'degenerative_polyarthritis': 17, 'hypothyroidism': 18, 'anxiety_state': 19,
                  'malignant_neoplasms': 20, 'acquired_immuno-deficiency_syndrome': 21, 'cellulitis': 22,
                  'gastroesophageal_reflux_disease': 23, 'septicemia': 24, 'deep_vein_thrombosis': 25,
                  'dehydration': 26, 'neoplasm': 27, 'embolism_pulmonary': 28, 'epilepsy': 29, 'cardiomyopathy': 30,
                  'chronic_kidney_failure': 31, 'carcinoma': 32, 'hepatitis_c': 33, 'peripheral_vascular_disease': 34,
                  'psychotic_disorder': 35, 'hyperlipidemia': 36, 'bipolar_disorder': 37, 'obesity': 38, 'ischemia': 39,
                  'cirrhosis': 40, 'exanthema': 41, 'benign_prostatic_hypertrophy': 42, 'kidney_failure_acute': 43,
                  'mitral_valve_insufficiency': 44, 'arthritis': 45, 'bronchitis': 46, 'hemiparesis': 47,
                  'osteoporosis': 48, 'transient_ischemic_attack': 49, 'adenocarcinoma': 50, 'paranoia': 51,
                  'pancreatitis': 52, 'incontinence': 53, 'paroxysmal_dyspnea': 54, 'hernia': 55,
                  'malignant_neoplasm_prostate': 56, 'edema_pulmonary': 57, 'lymphatic_diseases': 58,
                  'stenosis_aortic_valve': 59, 'malignant_neoplasm_breast': 60, 'schizophrenia': 61,
                  'diverticulitis': 62, 'overload_fluid': 63, 'ulcer_peptic': 64, 'osteomyelitis': 65, 'gastritis': 66,
                  'bacteremia': 67, 'failure_kidney': 68, 'sickle_cell_anemia': 69, 'failure_heart': 70,
                  'upper_respiratory_infection': 71, 'hepatitis': 72, 'hypertension_pulmonary': 73,
                  'deglutition_disorder': 74, 'gout': 75, 'thrombocytopaenia': 76, 'hypoglycemia': 77,
                  'pneumonia_aspiration': 78, 'colitis': 79, 'diverticulosis': 80, 'suicide_attempt': 81,
                  'pneumocystis_carinii_pneumonia': 82, 'hepatitis_b': 83, 'parkinson_disease': 84, 'lymphoma': 85,
                  'hyperglycemia': 86, 'encephalopathy': 87, 'tricuspid_valve_insufficiency': 88,
                  "alzheimer's_disease": 89, 'candidiasis': 90, 'neuropathy': 91, 'kidney_disease': 92,
                  'fibroid_tumor': 93, 'glaucoma': 94, 'neoplasm_metastasis': 95, 'malignant_tumor_colon': 96,
                  'ketoacidosis_diabetic': 97, 'tonic-clonic_epilepsy': 98, 'respiratory_failure': 99, 'melanoma': 100,
                  'gastroenteritis': 101, 'malignant_neoplasm_lung': 102, 'manic_disorder': 103,
                  'personality_disorder': 104, 'primary_carcinoma_liver_cells': 105, 'emphysema_pulmonary': 106,
                  'hemorrhoids': 107, 'spasm_bronchial': 108, 'aphasia': 109, 'obesity_morbid': 110,
                  'pyelonephritis': 111, 'endocarditis': 112, 'effusion_pericardial': 113,
                  'chronic_alcoholic_intoxication': 114, 'pneumothorax': 115, 'delirium': 116, 'neutropenia': 117,
                  'hyperbilirubinemia': 118, 'influenza': 119, 'dependence': 120, 'thrombus': 121, 'cholecystitis': 122,
                  'hernia_hiatal': 123, 'migraine_disorders': 124, 'pancytopenia': 125, 'cholelithiasis': 126,
                  'tachycardia_sinus': 127, 'ileus': 128, 'adhesion': 129, 'delusion': 130, 'affect_labile': 131,
                  'decubitus_ulcer': 132}
    extra_symptoms_to_id = {'-': 241,
                            '0': 178,
                            '0 gravida': 178,
                            '1': 379,
                            '1 para': 379,
                            '10': 353,
                            '10 gravida': 353,
                            '2': 338,
                            '2 para': 335,
                            '2 pregnancies previous': 338,
                            'abdomen': 390,
                            'abdomen acute': 390,
                            'abdomen distended': 180,
                            'abdominal': 333,
                            'abdominal bloating': 333,
                            'abdominal colic': 267,
                            'abdominal pain': 153,
                            'abdominal tenderness': 111,
                            'abnormal': 364,
                            'abnormal coordination': 364,
                            'abnormal sensation': 220,
                            'abnormally': 340,
                            'abnormally hard consistency': 340,
                            'abortion': 336,
                            'abscess': 82,
                            'abscess bacterial': 82,
                            'absences': 324,
                            'absences finding': 324,
                            'absent': 250,
                            'absent pulse': 250,
                            'abusive': 360,
                            'achalasia': 296,
                            'ache': 181,
                            'activity': 362,
                            'activity motor increased showing behavior': 362,
                            'acute': 390,
                            'acute abdomen': 390,
                            'adverse': 332,
                            'adverse reaction': 332,
                            'affect': 315,
                            'affect inappropriate': 315,
                            'aggravating': 69,
                            'agitation': 32,
                            'air': 391,
                            'air fluid level': 391,
                            'alcohol': 389,
                            'alcohol binge episode': 389,
                            'alcoholic': 310,
                            'alcoholic withdrawal symptoms': 310,
                            'allergies': 367,
                            'allergies drug known': 367,
                            'ambidexterity': 351,
                            'angina': 10,
                            'angina pectoris': 10,
                            'angle': 87,
                            'anorexia': 161,
                            'anosmia': 162,
                            'aphagia': 218,
                            'apyrexial': 84,
                            'arthralgia': 103,
                            'ascites': 115,
                            'associations': 196,
                            'associations loose': 196,
                            'asterixis': 118,
                            'asthenia': 3,
                            'asymptomatic': 202,
                            'ataxia': 255,
                            'atrial': 173,
                            'atypia': 211,
                            'auditory': 35,
                            'auditory hallucinations': 22,
                            'aura': 169,
                            'awakening': 305,
                            'awakening early': 305,
                            'back': 368,
                            'back pain': 101,
                            'bacterial': 82,
                            'bacterial abscess': 82,
                            'barking': 286,
                            'barking cough': 286,
                            'bedridden': 110,
                            'behavior': 362,
                            'behavior abusive verbally': 360,
                            'behavior hyperactive': 187,
                            'behavior showing increased motor activity': 362,
                            'belief': 131,
                            'belief religious': 131,
                            'binge': 389,
                            'blackout': 28,
                            'blanch': 358,
                            'bleeding': 337,
                            'bleeding heavy intermenstrual': 337,
                            'bleeding vagina': 204,
                            'bloating': 333,
                            'bloating abdominal': 333,
                            'blotches': 266,
                            'blotches red': 266,
                            'blurred': 231,
                            'blurred vision': 231,
                            'body': 138,
                            'bound': 172,
                            'bound wheelchair': 172,
                            'bowel': 366,
                            'bowel sounds decreased': 366,
                            'bradycardia': 75,
                            'bradykinesia': 228,
                            'breakthrough': 282,
                            'breakthrough pain': 282,
                            'breast': 260,
                            'breast mass': 260,
                            'breath': 392,
                            'breath catching': 392,
                            'breath gasping': 385,
                            'breath shortness': 1,
                            'breath sounds decreased': 50,
                            'breath-holding': 355,
                            'breath-holding spell': 355,
                            'breathing': 287,
                            'breathing labored': 19,
                            'breathing shallow rapid': 287,
                            'breech': 155,
                            'breech presentation': 155,
                            'bruit': 354,
                            'burning': 148,
                            'burning sensation': 148,
                            'cachexia': 208,
                            'caliber': 235,
                            'caliber stool decreased': 235,
                            'cardiomegaly': 158,
                            'cardiovascular': 376,
                            'cardiovascular finding': 376,
                            'catatonia': 175,
                            'catching': 392,
                            'catching breath': 392,
                            'cell': 96,
                            'change': 281,
                            'change emphysematous': 137,
                            'change status': 281,
                            'changes': 17,
                            'changes status mental': 17,
                            'charleyhorse': 369,
                            'chest': 74,
                            'chest discomfort': 74,
                            'chest pain': 0,
                            'chest pressure': 11,
                            'chest tightness': 43,
                            'chill': 51,
                            'choke': 365,
                            'cicatrisation': 167,
                            'clammy': 302,
                            'clammy skin': 302,
                            'clear': 92,
                            'clear consciousness': 92,
                            'clonus': 159,
                            'clumsiness': 234,
                            'cognition': 327,
                            'cognition impaired': 327,
                            'colic': 267,
                            'colic abdominal': 267,
                            'color': 240,
                            'compliance': 108,
                            'compliance non patient': 108,
                            'concentrate': 39,
                            'concentrate unable': 39,
                            'consciousness': 92,
                            'consciousness clear': 92,
                            'consistency': 340,
                            'consistency hard abnormally': 340,
                            'constipation': 152,
                            'coordination': 364,
                            'coordination abnormal': 364,
                            'cough': 286,
                            'cough barking': 286,
                            'cough hacking': 215,
                            'cough non-productive': 54,
                            'cough productive': 47,
                            'cushingoid': 136,
                            'cushingoid facies': 136,
                            'cyanosis': 156,
                            'cystic': 291,
                            'cystic lesion': 291,
                            'debilitation': 326,
                            'decompensation': 239,
                            'decreased': 366,
                            'decreased body weight': 138,
                            'decreased hematocrit': 165,
                            'decreased sounds bowel': 366,
                            'decreased sounds breath': 50,
                            'decreased stool caliber': 235,
                            'decreased translucency': 46,
                            'dentition': 313,
                            'dentition poor': 313,
                            'depressed': 29,
                            'depressed mood': 29,
                            'depression': 71,
                            'depression segment st': 71,
                            'diarrhea': 81,
                            'difficulty': 91,
                            'difficulty passing urine': 91,
                            'discharge': 289,
                            'discomfort': 151,
                            'discomfort chest': 74,
                            'discomfort general': 125,
                            'discomfort sensory': 151,
                            'disequilibrium': 273,
                            'disorder': 193,
                            'disorder hyperhidrosis': 193,
                            'distended': 180,
                            'distended abdomen': 180,
                            'distention': 61,
                            'distention venous jugular': 61,
                            'distress': 57,
                            'distress respiratory': 57,
                            'disturbed': 191,
                            'disturbed family': 191,
                            'dizziness': 2,
                            'dizzy': 343,
                            'dizzy spells': 343,
                            'drool': 328,
                            'drowsiness': 126,
                            'drug': 367,
                            'dullness': 265,
                            'dysarthria': 63,
                            'dysdiadochokinesia': 295,
                            'dysesthesia': 251,
                            'dyspareunia': 312,
                            'dyspnea': 62,
                            'dyspnea exertion': 42,
                            'dysuria': 85,
                            'early': 305,
                            'early awakening': 305,
                            'early satiety': 149,
                            'ecchymosis': 95,
                            'egophony': 237,
                            'ejection': 284,
                            'elation': 359,
                            'elevation': 70,
                            'elevation segment st': 70,
                            'emphysematous': 137,
                            'emphysematous change': 137,
                            'energy': 36,
                            'energy increased': 36,
                            'enuresis': 117,
                            'episode': 389,
                            'episode binge alcohol': 389,
                            'erythema': 78,
                            'estrogen': 262,
                            'estrogen use': 262,
                            'excruciating': 247,
                            'excruciating pain': 247,
                            'exertion': 42,
                            'exertion dyspnea': 42,
                            'exhaustion': 280,
                            'exhaustion extreme': 280,
                            'extrapyramidal': 195,
                            'extrapyramidal sign': 195,
                            'extreme': 280,
                            'extreme exhaustion': 280,
                            'eyes': 350,
                            'eyes rolling': 350,
                            'facial': 65,
                            'facial paresis': 65,
                            'facies': 136,
                            'facies cushingoid': 136,
                            'factors': 69,
                            'factors aggravating symptom': 69,
                            'fall': 4,
                            'falling': 244,
                            'falling fear': 244,
                            'family': 191,
                            'family disturbed': 191,
                            'fatigability': 334,
                            'fatigue': 99,
                            'fear': 244,
                            'fear falling': 244,
                            'feature': 199,
                            'feature wave r': 199,
                            'fecaluria': 307,
                            'feces': 386,
                            'feces rectum': 386,
                            'feeding': 316,
                            'feeding poor': 316,
                            'feeling': 322,
                            'feeling heavy': 183,
                            'feeling hopeless': 23,
                            'feeling strange': 322,
                            'feeling suicidal': 20,
                            'feels': 371,
                            'feels hot/feverish': 371,
                            'fetus': 393,
                            'fetus large-for-dates': 393,
                            'fever': 45,
                            'finding': 376,
                            'finding absences': 324,
                            'finding cardiovascular': 376,
                            'flare': 372,
                            'flaring': 380,
                            'flaring nasal': 380,
                            'flatulence': 384,
                            'floppy': 314,
                            'fluid': 391,
                            'flush': 134,
                            'flush hot': 134,
                            'flushing': 274,
                            'focal': 219,
                            'focal seizures': 219,
                            'food': 123,
                            'food intolerance': 123,
                            'foot': 271,
                            'foot pain': 271,
                            'formication': 133,
                            'frail': 290,
                            'fremitus': 222,
                            'friction': 373,
                            'frothy': 259,
                            'frothy sputum': 259,
                            'gag': 248,
                            'gain': 129,
                            'gain weight': 129,
                            'gait': 112,
                            'gait unsteady': 112,
                            'gasping': 385,
                            'gasping breath': 385,
                            'general': 212,
                            'general discomfort': 125,
                            'general unsteadiness': 212,
                            'giddy': 190,
                            'giddy mood': 190,
                            'gravida': 353,
                            'gravida 0': 178,
                            'gravida 10': 353,
                            'green': 53,
                            'green sputum': 53,
                            'groggy': 331,
                            'guaiac': 93,
                            'guaiac positive': 93,
                            'gurgle': 171,
                            'hacking': 215,
                            'hacking cough': 215,
                            'haemoptysis': 56,
                            'haemorrhage': 97,
                            'hallucinations': 35,
                            'hallucinations auditory': 22,
                            'hallucinations auditory verbal': 35,
                            'hallucinations visual': 30,
                            'hand': 124,
                            'hand numbness': 124,
                            'hard': 340,
                            'headache': 121,
                            'heartburn': 154,
                            'heavy': 337,
                            'heavy feeling': 183,
                            'heavy legs': 293,
                            "heberden's": 256,
                            "heberden's node": 256,
                            'hematochezia': 236,
                            'hematocrit': 165,
                            'hematocrit decreased': 165,
                            'hematuria': 86,
                            'heme': 100,
                            'heme positive': 100,
                            'hemianopsia': 164,
                            'hemianopsia homonymous': 164,
                            'hemiplegia': 66,
                            'hemodynamically': 90,
                            'hemodynamically stable': 90,
                            'hepatomegaly': 257,
                            'hepatosplenomegaly': 79,
                            'hesitation': 272,
                            'hesitation urinary': 272,
                            'hirsutism': 226,
                            'hoard': 374,
                            'hoarseness': 139,
                            'homelessness': 40,
                            'homicidal': 395,
                            'homicidal thoughts': 395,
                            'homonymous': 164,
                            'homonymous hemianopsia': 164,
                            'hopeless': 23,
                            'hopeless feeling': 23,
                            'hot': 134,
                            'hot flush': 134,
                            'hot/feverish': 371,
                            'hot/feverish feels': 371,
                            'hunger': 269,
                            'hydropneumothorax': 320,
                            'hyperactive': 187,
                            'hyperactive behavior': 187,
                            'hyperacusis': 145,
                            'hypercapnia': 107,
                            'hyperemesis': 345,
                            'hyperhidrosis': 193,
                            'hyperhidrosis disorder': 193,
                            'hyperkalemia': 113,
                            'hypersomnia': 192,
                            'hypersomnolence': 263,
                            'hypertonicity': 382,
                            'hypertrophy': 173,
                            'hypertrophy atrial left': 173,
                            'hyperventilation': 246,
                            'hypesthesia': 144,
                            'hypoalbuminemia': 277,
                            'hypocalcemia': 209,
                            'hypocalcemia result': 209,
                            'hypokalemia': 268,
                            'hypokinesia': 41,
                            'hypometabolism': 168,
                            'hyponatremia': 89,
                            'hypoproteinemia': 388,
                            'hypotension': 116,
                            'hypothermia,': 210,
                            'hypothermia, natural': 210,
                            'hypotonia': 142,
                            'hypotonia muscle': 142,
                            'hypoxemia': 106,
                            'icterus': 356,
                            'icterus scleral': 356,
                            'immobile': 394,
                            'impaired': 327,
                            'impaired cognition': 327,
                            'inappropriate': 315,
                            'inappropriate affect': 315,
                            'incoherent': 300,
                            'incontinence': 230,
                            'incontinence urge': 230,
                            'increased': 362,
                            'increased energy': 36,
                            'indifferent': 275,
                            'indifferent mood': 275,
                            'intermenstrual': 337,
                            'intermenstrual heavy bleeding': 337,
                            'interval': 254,
                            'intolerance': 123,
                            'intolerance food': 123,
                            'intoxication': 34,
                            'invasion': 96,
                            'invasion cell tumor': 96,
                            'inverted': 72,
                            'inverted wave': 72,
                            'irritable': 27,
                            'irritable mood': 27,
                            'jugular': 61,
                            'jugular venous distention': 61,
                            'known': 367,
                            'known drug allergies': 367,
                            'labored': 19,
                            'labored breathing': 19,
                            'lameness': 301,
                            'large-for-dates': 393,
                            'large-for-dates fetus': 393,
                            'left': 173,
                            'left atrial hypertrophy': 173,
                            'legs': 293,
                            'legs heavy': 293,
                            'lesion': 291,
                            'lesion cystic': 291,
                            'lesion metastatic': 163,
                            'lethargy': 88,
                            'level': 391,
                            'level fluid air': 391,
                            'lightheadedness': 122,
                            'limb': 157,
                            'limb lower pain': 157,
                            'line': 223,
                            "line stahli's": 223,
                            'lip': 348,
                            'lip smacking': 348,
                            'loose': 196,
                            'loose associations': 196,
                            'low': 368,
                            'low back pain': 368,
                            'lower': 157,
                            'lung': 179,
                            'lung nodule': 179,
                            'macerated': 182,
                            'macerated skin': 182,
                            'macule': 205,
                            'malaise': 59,
                            'marks': 146,
                            'marks scratch': 146,
                            'mass': 260,
                            'mass body structure': 130,
                            'mass breast': 260,
                            'mediastinal': 303,
                            'mediastinal shift': 303,
                            'membranes': 141,
                            'membranes rupture spontaneous': 141,
                            'mental': 17,
                            'mental status changes': 17,
                            'metastatic': 163,
                            'metastatic lesion': 163,
                            'micturition': 114,
                            'micturition urgency': 114,
                            'milky': 346,
                            'moan': 317,
                            'monoclonal': 94,
                            'monocytosis': 298,
                            'mood': 275,
                            'mood depressed': 29,
                            'mood giddy': 190,
                            'mood indifferent': 275,
                            'mood irritable': 27,
                            'moody': 243,
                            'motor': 362,
                            'motor retardation': 26,
                            'murmur': 284,
                            'murmur ejection systolic': 284,
                            'murmur pansystolic': 283,
                            'murmur systolic': 201,
                            "murphy's": 383,
                            "murphy's sign": 383,
                            'muscle': 142,
                            'muscle hypotonia': 142,
                            'muscle twitch': 119,
                            'myalgia': 311,
                            'mydriasis': 194,
                            'myoclonus': 170,
                            'nasal': 380,
                            'nasal discharge present': 289,
                            'nasal flaring': 380,
                            'natural': 210,
                            'natural hypothermia,': 210,
                            'nausea': 304,
                            'nausea vomiting': 304,
                            'neck': 342,
                            'neck pain': 342,
                            'neck stiffness': 166,
                            'neologism': 238,
                            'nervousness': 132,
                            'night': 60,
                            'night sweat': 60,
                            'nightmare': 38,
                            'node': 256,
                            "node heberden's": 256,
                            'nodule': 179,
                            'nodule lung': 179,
                            'noisy': 288,
                            'noisy respiration': 288,
                            'non': 108,
                            'non-productive': 54,
                            'non-productive cough': 54,
                            'nonsmoker': 77,
                            'nose': 285,
                            'nose stuffy': 285,
                            'numbness': 124,
                            'numbness hand': 124,
                            'observation': 241,
                            'observation temperature-associated - rigor': 241,
                            'oliguria': 174,
                            'orthopnea': 14,
                            'orthostasis': 102,
                            'overweight': 200,
                            'pain': 368,
                            'pain abdominal': 153,
                            'pain back': 101,
                            'pain back low': 368,
                            'pain breakthrough': 282,
                            'pain chest': 0,
                            'pain excruciating': 247,
                            'pain foot': 271,
                            'pain lower limb': 157,
                            'pain neck': 342,
                            'pain pleuritic': 48,
                            'pain rest': 184,
                            'pain shooting': 344,
                            'pain side': 297,
                            'painful': 207,
                            'painful swallowing': 207,
                            'pallor': 98,
                            'palpitation': 8,
                            'panic': 375,
                            'pansystolic': 283,
                            'pansystolic murmur': 283,
                            'para': 379,
                            'para 1': 379,
                            'para 2': 335,
                            'paradoxus': 352,
                            'paradoxus pulsus': 352,
                            'paralyse': 225,
                            'paralysis': 309,
                            'paralysis todd': 309,
                            'paraparesis': 242,
                            'paresis': 217,
                            'paresis facial': 65,
                            'paresthesia': 177,
                            'passed': 253,
                            'passed stones': 253,
                            'passing': 91,
                            'patient': 108,
                            'patient non compliance': 108,
                            'pectoris': 10,
                            'pectoris angina': 10,
                            'pericardial': 373,
                            'pericardial friction rub': 373,
                            'phonophobia': 349,
                            'photophobia': 206,
                            'photopsia': 189,
                            'pin-point': 329,
                            'pin-point pupils': 329,
                            'pleuritic': 48,
                            'pleuritic pain': 48,
                            'pneumatouria': 308,
                            'polydypsia': 13,
                            'polymyalgia': 252,
                            'polyuria': 12,
                            'poor': 316,
                            'poor dentition': 313,
                            'poor feeding': 316,
                            'positive': 378,
                            'positive guaiac': 93,
                            'positive heme': 100,
                            'positive rhd': 378,
                            'posterior': 299,
                            'posterior rhinorrhea': 299,
                            'posturing': 249,
                            'pregnancies': 338,
                            'presence': 73,
                            'presence q wave': 73,
                            'present': 289,
                            'present discharge nasal': 289,
                            'presentation': 155,
                            'presentation breech': 155,
                            'pressure': 11,
                            'pressure chest': 11,
                            'previous': 338,
                            'previous pregnancies 2': 338,
                            'primigravida': 339,
                            'prodrome': 387,
                            'productive': 47,
                            'productive cough': 47,
                            'projectile': 292,
                            'projectile vomiting': 292,
                            'prolonged': 254,
                            'prolonged interval qt': 254,
                            'prostate': 270,
                            'prostate tender': 270,
                            'prostatism': 128,
                            'proteinemia': 341,
                            'pruritus': 80,
                            'pulse': 250,
                            'pulse absent': 250,
                            'pulsus': 352,
                            'pulsus paradoxus': 352,
                            'pupils': 329,
                            'pupils pin-point': 329,
                            'purulent': 105,
                            'purulent sputum': 105,
                            'pustule': 278,
                            'q': 73,
                            'qt': 254,
                            'qt interval prolonged': 254,
                            'quality': 150,
                            'quality sensation throbbing': 150,
                            'r': 199,
                            'r wave feature': 199,
                            'rale': 15,
                            'rambling': 233,
                            'rambling speech': 233,
                            'rapid': 287,
                            'rapid shallow breathing': 287,
                            'reaction': 332,
                            'reaction adverse': 332,
                            'rectum': 386,
                            'rectum feces': 386,
                            'red': 266,
                            'red blotches': 266,
                            'redness': 143,
                            'regurgitates': 347,
                            'regurgitates swallowing': 347,
                            'religious': 131,
                            'religious belief': 131,
                            'renal': 87,
                            'renal angle tenderness': 87,
                            'respiration': 288,
                            'respiration noisy': 288,
                            'respiratory': 57,
                            'respiratory distress': 57,
                            'rest': 184,
                            'rest pain': 184,
                            'resting': 330,
                            'resting tremor': 330,
                            'result': 209,
                            'result hypocalcemia': 209,
                            'retardation': 26,
                            'retardation motor': 26,
                            'retch': 357,
                            'retropulsion': 261,
                            'rhd': 378,
                            'rhd positive': 378,
                            'rhinorrhea': 299,
                            'rhinorrhea posterior': 299,
                            'rhonchus': 52,
                            'rhythm': 185,
                            'rhythm sinus': 185,
                            'rigor': 241,
                            'rigor - temperature-associated observation': 241,
                            'rolling': 350,
                            'rolling eyes': 350,
                            'room': 232,
                            'room spinning': 232,
                            'rub': 373,
                            'rub friction pericardial': 373,
                            'rupture': 141,
                            'satiety': 149,
                            'satiety early': 149,
                            'scar': 363,
                            'scar tissue': 363,
                            'sciatica': 258,
                            'scleral': 356,
                            'scleral icterus': 356,
                            'scratch': 146,
                            'scratch marks': 146,
                            'sedentary': 370,
                            'segment': 71,
                            'seizure': 67,
                            'seizures': 325,
                            'seizures focal': 219,
                            'seizures tonic': 325,
                            'sensation': 224,
                            'sensation abnormal': 220,
                            'sensation burning': 148,
                            'sensation stinging': 224,
                            'sensory': 151,
                            'sensory discomfort': 151,
                            'shallow': 287,
                            'shift': 303,
                            'shift mediastinal': 303,
                            'shooting': 344,
                            'shooting pain': 344,
                            'shortness': 1,
                            'shortness breath': 1,
                            'showing': 362,
                            'side': 297,
                            'side pain': 297,
                            'sign': 383,
                            'sign extrapyramidal': 195,
                            "sign murphy's": 383,
                            'sinus': 185,
                            'sinus rhythm': 185,
                            'skin': 302,
                            'skin clammy': 302,
                            'skin macerated': 182,
                            'sleeplessness': 25,
                            'sleepy': 120,
                            'slowing': 279,
                            'slowing urinary stream': 279,
                            'slurred': 64,
                            'slurred speech': 64,
                            'smacking': 348,
                            'smacking lip': 348,
                            'sneeze': 381,
                            'sniffle': 227,
                            'snore': 198,
                            'snuffle': 214,
                            'soft': 377,
                            'soft tissue swelling': 377,
                            'sore': 213,
                            'sore throat': 213,
                            'sore touch': 147,
                            'sounds': 366,
                            'spasm': 245,
                            'speech': 233,
                            'speech rambling': 233,
                            'speech slurred': 64,
                            'spell': 355,
                            'spell breath-holding': 355,
                            'spells': 343,
                            'spells dizzy': 343,
                            'spinning': 232,
                            'spinning room': 232,
                            'splenomegaly': 203,
                            'spontaneous': 141,
                            'spontaneous rupture membranes': 141,
                            'sputum': 259,
                            'sputum frothy': 259,
                            'sputum green': 53,
                            'sputum purulent': 105,
                            'sputum yellow': 49,
                            'st': 71,
                            'st segment depression': 71,
                            'st segment elevation': 70,
                            'stable': 90,
                            'stable hemodynamically': 90,
                            "stahli's": 223,
                            "stahli's line": 223,
                            'state': 109,
                            'state unconscious': 109,
                            'status': 281,
                            'status change': 281,
                            'stiffness': 166,
                            'stiffness neck': 166,
                            'stinging': 224,
                            'stinging sensation': 224,
                            'stones': 253,
                            'stones passed': 253,
                            'stool': 240,
                            'stool color yellow': 240,
                            'strange': 322,
                            'strange feeling': 322,
                            'stream': 279,
                            'stream urinary slowing': 279,
                            'stridor': 216,
                            'structure': 130,
                            'structure body mass': 130,
                            'stuffy': 285,
                            'stuffy nose': 285,
                            'stupor': 221,
                            'suicidal': 21,
                            'suicidal feeling': 20,
                            'superimposition': 321,
                            'swallowing': 347,
                            'swallowing painful': 207,
                            'swallowing regurgitates': 347,
                            'sweat': 60,
                            'sweat night': 60,
                            'swelling': 377,
                            'swelling tissue soft': 377,
                            'symptom': 69,
                            'symptom aggravating factors': 69,
                            'symptoms': 310,
                            'symptoms withdrawal alcoholic': 310,
                            'syncope': 5,
                            'systolic': 284,
                            'systolic ejection murmur': 284,
                            'systolic murmur': 201,
                            'tachypnea': 58,
                            'temperature-associated': 241,
                            'tender': 270,
                            'tender prostate': 270,
                            'tenderness': 111,
                            'tenderness abdominal': 111,
                            'tenderness angle renal': 87,
                            'tenesmus': 306,
                            'terrify': 188,
                            'thicken': 140,
                            'thoughts': 395,
                            'thoughts homicidal': 395,
                            'throat': 213,
                            'throat sore': 213,
                            'throbbing': 150,
                            'throbbing sensation quality': 150,
                            'tightness': 43,
                            'tightness chest': 43,
                            'tinnitus': 319,
                            'tissue': 377,
                            'tissue scar': 363,
                            'titubation': 294,
                            'todd': 309,
                            'todd paralysis': 309,
                            'tonic': 325,
                            'tonic seizures': 325,
                            'touch': 147,
                            'touch sore': 147,
                            'transaminitis': 104,
                            'translucency': 46,
                            'translucency decreased': 46,
                            'transsexual': 361,
                            'tremor': 330,
                            'tremor resting': 330,
                            'tumor': 96,
                            'tumor cell invasion': 96,
                            'twitch': 119,
                            'twitch muscle': 119,
                            'unable': 39,
                            'unable concentrate': 39,
                            'unconscious': 109,
                            'unconscious state': 109,
                            'uncoordination': 323,
                            'underweight': 264,
                            'unhappy': 176,
                            'unresponsiveness': 16,
                            'unsteadiness': 212,
                            'unsteadiness general': 212,
                            'unsteady': 112,
                            'unsteady gait': 112,
                            'unwell': 160,
                            'urge': 230,
                            'urge incontinence': 230,
                            'urgency': 114,
                            'urgency micturition': 114,
                            'urinary': 279,
                            'urinary hesitation': 272,
                            'urine': 91,
                            'urine passing difficulty': 91,
                            'urinoma': 276,
                            'use': 262,
                            'use estrogen': 262,
                            'vagina': 204,
                            'vagina bleeding': 204,
                            'venous': 61,
                            'verbal': 35,
                            'verbal auditory hallucinations': 35,
                            'verbally': 360,
                            'verbally abusive behavior': 360,
                            'vertigo': 6,
                            'vision': 231,
                            'vision blurred': 231,
                            'visual': 30,
                            'visual hallucinations': 30,
                            'vomiting': 304,
                            'vomiting nausea': 304,
                            'vomiting projectile': 292,
                            'wave': 199,
                            'wave inverted': 72,
                            'wave q presence': 73,
                            'weepiness': 24,
                            'weight': 138,
                            'weight body decreased': 138,
                            'weight gain': 129,
                            'welt': 318,
                            'wheelchair': 172,
                            'wheelchair bound': 172,
                            'wheezing': 55,
                            'withdraw': 186,
                            'withdrawal': 310,
                            'worry': 31,
                            'yellow': 240,
                            'yellow color stool': 240,
                            'yellow sputum': 49}

    id2disease= {0: 'hypertensive_disease', 1: 'diabetes', 2: 'depression_mental', 3: 'coronary_arteriosclerosis', 4: 'pneumonia', 5: 'failure_heart_congestive', 6: 'accident_cerebrovascular', 7: 'asthma', 8: 'myocardial_infarction', 9: 'hypercholesterolemia', 10: 'infection', 11: 'infection_urinary_tract', 12: 'anemia', 13: 'chronic_obstructive_airway_disease', 14: 'dementia', 15: 'insufficiency_renal', 16: 'confusion', 17: 'degenerative_polyarthritis', 18: 'hypothyroidism', 19: 'anxiety_state', 20: 'malignant_neoplasms', 21: 'acquired_immuno-deficiency_syndrome', 22: 'cellulitis', 23: 'gastroesophageal_reflux_disease', 24: 'septicemia', 25: 'deep_vein_thrombosis', 26: 'dehydration', 27: 'neoplasm', 28: 'embolism_pulmonary', 29: 'epilepsy', 30: 'cardiomyopathy', 31: 'chronic_kidney_failure', 32: 'carcinoma', 33: 'hepatitis_c', 34: 'peripheral_vascular_disease', 35: 'psychotic_disorder', 36: 'hyperlipidemia', 37: 'bipolar_disorder', 38: 'obesity', 39: 'ischemia', 40: 'cirrhosis', 41: 'exanthema', 42: 'benign_prostatic_hypertrophy', 43: 'kidney_failure_acute', 44: 'mitral_valve_insufficiency', 45: 'arthritis', 46: 'bronchitis', 47: 'hemiparesis', 48: 'osteoporosis', 49: 'transient_ischemic_attack', 50: 'adenocarcinoma', 51: 'paranoia', 52: 'pancreatitis', 53: 'incontinence', 54: 'paroxysmal_dyspnea', 55: 'hernia', 56: 'malignant_neoplasm_prostate', 57: 'edema_pulmonary', 58: 'lymphatic_diseases', 59: 'stenosis_aortic_valve', 60: 'malignant_neoplasm_breast', 61: 'schizophrenia', 62: 'diverticulitis', 63: 'overload_fluid', 64: 'ulcer_peptic', 65: 'osteomyelitis', 66: 'gastritis', 67: 'bacteremia', 68: 'failure_kidney', 69: 'sickle_cell_anemia', 70: 'failure_heart', 71: 'upper_respiratory_infection', 72: 'hepatitis', 73: 'hypertension_pulmonary', 74: 'deglutition_disorder', 75: 'gout', 76: 'thrombocytopaenia', 77: 'hypoglycemia', 78: 'pneumonia_aspiration', 79: 'colitis', 80: 'diverticulosis', 81: 'suicide_attempt', 82: 'pneumocystis_carinii_pneumonia', 83: 'hepatitis_b', 84: 'parkinson_disease', 85: 'lymphoma', 86: 'hyperglycemia', 87: 'encephalopathy', 88: 'tricuspid_valve_insufficiency', 89: "alzheimer's_disease", 90: 'candidiasis', 91: 'neuropathy', 92: 'kidney_disease', 93: 'fibroid_tumor', 94: 'glaucoma', 95: 'neoplasm_metastasis', 96: 'malignant_tumor_colon', 97: 'ketoacidosis_diabetic', 98: 'tonic-clonic_epilepsy', 99: 'respiratory_failure', 100: 'melanoma', 101: 'gastroenteritis', 102: 'malignant_neoplasm_lung', 103: 'manic_disorder', 104: 'personality_disorder', 105: 'primary_carcinoma_liver_cells', 106: 'emphysema_pulmonary', 107: 'hemorrhoids', 108: 'spasm_bronchial', 109: 'aphasia', 110: 'obesity_morbid', 111: 'pyelonephritis', 112: 'endocarditis', 113: 'effusion_pericardial', 114: 'chronic_alcoholic_intoxication', 115: 'pneumothorax', 116: 'delirium', 117: 'neutropenia', 118: 'hyperbilirubinemia', 119: 'influenza', 120: 'dependence', 121: 'thrombus', 122: 'cholecystitis', 123: 'hernia_hiatal', 124: 'migraine_disorders', 125: 'pancytopenia', 126: 'cholelithiasis', 127: 'tachycardia_sinus', 128: 'ileus', 129: 'adhesion', 130: 'delusion', 131: 'affect_labile', 132: 'decubitus_ulcer'}



if __name__=="__main__":
   predict_disease("i have seizures. I have hypermetabolism. I have tremors. I am unresponsive".split("."))
